# Generated by Django 2.0.5 on 2018-06-06 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(default='11111111-1', max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('alumnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='universidad.Alumno')),
                ('profesor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='usuarios.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('carreras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultad', to='universidad.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_imagen', models.ImageField(default='rutaimagen', null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='cursos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrera', to='universidad.Curso'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='imagen',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='universidad.Imagen'),
        ),
    ]
