# Generated by Django 2.0.6 on 2018-06-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='cursos',
        ),
        migrations.AddField(
            model_name='carrera',
            name='cursos',
            field=models.ManyToManyField(related_name='carrera', to='universidad.Curso'),
        ),
        migrations.RemoveField(
            model_name='facultad',
            name='carreras',
        ),
        migrations.AddField(
            model_name='facultad',
            name='carreras',
            field=models.ManyToManyField(related_name='facultad', to='universidad.Carrera'),
        ),
    ]
