# Generated by Django 2.0.6 on 2018-06-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='imagen',
            field=models.ImageField(default='alumnos/None/no-img.jpg', null=True, upload_to='alumnos/'),
        ),
    ]
