# Generated by Django 2.0.6 on 2018-06-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0002_auto_20180614_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='imagen',
            field=models.ImageField(default='universidad/static/images/alumnos/None/no-img.jpg', null=True, upload_to='universidad/static/images/alumnos/'),
        ),
    ]
