# Generated by Django 2.0.6 on 2018-06-12 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0003_auto_20180610_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrera', to='universidad.Carrera'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
