# Generated by Django 2.0.6 on 2018-06-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0003_auto_20180614_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='imagen',
            field=models.ImageField(default='fotos_alumnos/None/no-img.jpg', null=True, upload_to='fotos_alumnos'),
        ),
    ]
