# Generated by Django 2.0.6 on 2018-06-12 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0004_auto_20180612_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ManyToManyField(to='universidad.Alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Curso')),
            ],
        ),
    ]
